name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: 'filecoin-project/lotus'
        ref: 'v1.17.1'

    - name: Get Dockerfile
      run: wget https://raw.githubusercontent.com/pyropy/fil-2k/master/Dockerfile.lotus-debug -O Dockerfile.lotus-debug

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      if: github.event_name != 'pull_request'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker meta
      id: lotus
      uses: docker/metadata-action@v3
      with:
        # list of Docker images to use as base name for tags
        images: |
          pyropy/lotus
        # Docker tags based on the following events/attributes
        tags: |
          type=schedule
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern=1.17.1
          type=semver,pattern=1.17
          type=semver,pattern=v1.17.1
          type=sha

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./
        file: Dockerfile.lotus-debug
        push: ${{ github.event_name != 'pull_request' }}
        target: lotus
        tags: ${{ steps.lotus.outputs.tags }}
        labels: ${{ steps.lotus.outputs.labels }}
